### ISSUE TITLE
Doubt about script execution

### ISSUE THREAD

**Issue by Oshtur95** [ArtemKushnerov/az#10]
Hi,

I execute the following command on Ubuntu's 19.10 terminal and got an error. So I wanted to know if I am executing right the command to download the apks or if I am missing something.

Command:
`az -n 10 -d 2015-12-11: -s :3000000 -m play.google.com,appchina
`

Error:
```
Traceback (most recent call last):
  File "/usr/local/bin/az", line 11, in <module>
    load_entry_point('azoo==1.3.0', 'console_scripts', 'az')()
  File "/home/claudiomori/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/claudiomori/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/home/claudiomori/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/home/claudiomori/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/claudiomori/.local/lib/python2.7/site-packages/modules/main.py", line 50
    number, *criteria_args, metadata, key, input_file = Parser(args).parse()
            ^
SyntaxError: invalid syntax
```

Before executing the command I installed the requirements indicated on the requirements.txt file and also followed the instructions on the Readme file.

Thank you in advance

**Comment by ArtemKushnerov** [comment]
Hi Oshtur. For now az runs on Python 3.6 only. Please try with the correct version and let me know if it works.
