### ISSUE TITLE
Got TypeError when processing "az"

### ISSUE THREAD

**Issue by h-un** [ArtemKushnerov/az#11]
I got an error when trying to process "az" in command line. How could I sovle it?

Traceback (most recent call last):
  File "C:\Python37\Scripts\az-script.py", line 11, in <module>
    load_entry_point('azoo==1.3.0', 'console_scripts', 'az')()
  File "C:\Python37\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python37\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Python37\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python37\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Python37\lib\site-packages\modules\main.py", line 52, in run
    az.run(input_file, key, number, criteria, out_dir=out if out else os.getcwd(), metadata=metadata, seed=seed, threads=threads)
  File "C:\Python37\lib\site-packages\modules\az.py", line 18, in run
    random_subset = RandomPicker(seed=seed).get_random_subset(dataset, number)
  File "C:\Python37\lib\site-packages\modules\services\random_picker.py", line 14, in get_random_subset
    for num, apk in enumerate(input_dataset, 1):
  File "C:\Python37\lib\site-packages\modules\entities\dataset\filtered_dataset.py", line 23, in __next__
    apk = next(self.source)
  File "C:\Python37\lib\site-packages\modules\entities\source.py", line 20, in __next__
    return Apk(*columns)
TypeError: __init__() takes from 1 to 12 positional arguments but 13 were given

**Comment by ArtemKushnerov** [comment]
Hello, h-un. Could you please provide a command you were using?

**Comment by h-un** [comment]
> Hello, h-un. Could you please provide a command you were using?

I used  "az -k <key> -i <path>" trying to download all the files.

**Comment by ArtemKushnerov** [comment]
@h-un ahh there a soo much of them, I don't recommend trying to download everything, better use some reasonable criteria. Looks like you got some extra columns in latest.csv, did you add something in there? And also is this command working for you az -n 10 -d 2015-12-11: -s :3000000 -m play.google.com,appchina ?

**Comment by h-un** [comment]
> @h-un ahh there a soo much of them, I don't recommend trying to download everything, better use some reasonable criteria. Looks like you got some extra columns in latest.csv, did you add something in there? And also is this command working for you az -n 10 -d 2015-12-11: -s :3000000 -m play.google.com,appchina ?

well, I tried "az -n 10 -d 2015-12-11: -s :3000000 -m play.google.com,appchina" and still got the same error.
TypeError: __init__() takes from 1 to 12 positional arguments but 13 were given

**Comment by ArtemKushnerov** [comment]
Okay, and did you edit your latest.csv?

**Comment by h-un** [comment]
> Okay, and did you edit your latest.csv?

No. I just downloaded and uncompressed it.

**Comment by h-un** [comment]
Does it need to be exactly Python 3.6? well I'm using Python3.7

**Comment by herningalex** [comment]
Hey there, I hope it's not considered breach of "issue ettiquette" to jump in like this but I'm getting the same behavior as @h-un, but I'm using Python 3.6 on Ubuntu 18.04.1 with sample arguments given in docs/az help. Likewise, I downloaded and decompressed latest.csv without alteration (to my knowledge).
 ```
$ az -n 10 -d 2015-12-11: -s :3000000  -m play.google.com,appchina
 2019-07-17 00:00:02,332 - INFO - START. APKS TO DOWNLOAD: 10
 2019-07-17 00:00:02,334 - INFO - CREATE DATASET BY CRITERIA: dex_date=(datetime.datetime(2015, 12, 11, 0, 0), None), apk_size=(None, 3000000), vt_detection=(None, None), markets={'play.google.com', 'appchina'}, pkg_name=None, sha256=None, sha1=None, md5=None
 Traceback (most recent call last):
  File "/home/alex/.local/bin/az", line 11, in <module>
    sys.exit(run())
  File "/home/alex/.local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/alex/.local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/alex/.local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/alex/.local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
>  File "/home/alex/.local/lib/python3.6/site-packages/modules/main.py", line 52, in run
    az.run(input_file, key, number, criteria, out_dir=out if out else os.getcwd(), metadata=metadata, seed=seed, threads=threads)
  File "/home/alex/.local/lib/python3.6/site-packages/modules/az.py", line 18, in run
    random_subset = RandomPicker(seed=seed).get_random_subset(dataset, number)
  File "/home/alex/.local/lib/python3.6/site-packages/modules/services/random_picker.py", line 14, in get_random_subset
    for num, apk in enumerate(input_dataset, 1):
  File "/home/alex/.local/lib/python3.6/site-packages/modules/entities/dataset/filtered_dataset.py", line 27, in __next__
    apk = next(self.source)
  File "/home/alex/.local/lib/python3.6/site-packages/modules/entities/source.py", line 20, in __next__
    return Apk(*columns)
TypeError: __init__() takes from 1 to 12 positional arguments but 13 were given
```
my ~/.az:
```
key=${KEY}
input_file=/home/alex/Documents/latest.csv
```
Let me know if there's any further information I can provide. Thanks!

**Comment by ArtemKushnerov** [comment]
Guys, try installing version 1.3.1 with pip install azoo -U. Make sure you got it with az --version. Then try your downloads again and please report.

**Comment by kallix** [comment]
Interesting...
I have to investigate how this app (BC564D52C6E79E1676C19D9602B1359A33B8714A1DC5FCB8ED602209D0B70266) managed to have a pkg_name with a ',' inside... Is that even a valid name / Would a phone accept such an app ? 

Anyway, it's because I feared something like that could happen that I decided to quote the whole field in the CSV.

**Comment by herningalex** [comment]
@ArtemKushnerov 1.3.1 is working for me

**Comment by h-un** [comment]
@ArtemKushnerov Working for me too, Thanks a lot

**Comment by ArtemKushnerov** [comment]
@kallix I don't really know, but think it's not valid

@herningalex @h-un cool guys, thanks for a feedback
