### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by AmrAshraf** [ArtemKushnerov/az#12]
Hello there,
I have a permission error on any where on my windows machine but how is it?! It should take at least my users' permissions. I have changed the input file sever times and get the following error:
 ```
Traceback (most recent call last):
 File "C:\Users\a.ashraf\AppData\Local\Programs\Python\Python37\Scripts\az-script.py", line 11, in <module>
    load_entry_point('azoo==1.3.1', 'console_scripts', 'az')()
  File "C:\Users\a.ashraf\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\a.ashraf\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\a.ashraf\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\a.ashraf\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\a.ashraf\AppData\Local\Programs\Python\Python37\lib\site-packages\modules\main.py", line 52, in run
    az.run(input_file, key, number, criteria, out_dir=out if out else os.getcwd(), metadata=metadata, seed=seed, threads=threads)
  File "C:\Users\a.ashraf\AppData\Local\Programs\Python\Python37\lib\site-packages\modules\az.py", line 15, in run
    source = Source(input_file=input_file)
  File "C:\Users\a.ashraf\AppData\Local\Programs\Python\Python37\lib\site-packages\modules\entities\source.py", line 9, in __init__
    self.input_file = open(input_file)
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\a.ashraf\\Desktop'
```

**Comment by ArtemKushnerov** [comment]
Hello @AmrAshraf . Try pointing to a file itself, like C:\\Users\\a.ashraf\\Desktop\latest.csv

**Comment by AmrAshraf** [comment]
@ArtemKushnerov i don't have "latest.csv" file as i try like `az -n 10 -d 2015-12-11: -s :3000000 -m play.google.com,appchina` which i think shouldn't require the file.

**Comment by ArtemKushnerov** [comment]
No it is always require the file, please download it from androzoo website.
