### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by liorko87** [ArtemKushnerov/az#14]
Hello,

I'm trying to run the sample from the README file and got this exception:

```
Traceback (most recent call last):
  File "/home/user/.local/bin/az", line 7, in <module>
    from modules.main import run
  File "/home/user/.local/lib/python2.7/site-packages/modules/main.py", line 50
    number, *criteria_args, metadata, key, input_file = Parser(args).parse()
            ^
SyntaxError: invalid syntax
```

I'm working on Ubuntu 18.04.

**Comment by b1ackm4x** [comment]
Hello, have you solved this problem? I meet the same problem

**Comment by ArtemKushnerov** [comment]
Correct, use 3.6.
