### ISSUE TITLE
Successfully installed but when I typed 'az' in command line I got errors

### ISSUE THREAD

**Issue by jy5380** [ArtemKushnerov/az#2]
Environment: Ubuntu16.04, Python3.5

I followed the instructions to install az on my ubuntu virtual machine

pip install -e git+https://github.com/ArtemKushnerov/az.git@v1.2.0#egg=az

then I got error says that the branch 1.2.0 doesn't exist, I checked the github release page and replace "1.2.0" with "1.0.1", and it worked. I got "Successfully installed" tips.
then I created .az file and fill my api key and the csv file path. 
When I typed az into commandline, I got the errors as following:

Traceback (most recent call last):
  File "/usr/local/bin/az", line 11, in <module>
    load_entry_point('az', 'console_scripts', 'az')()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/yuan/src/az/cli.py", line 6, in <module>
    from modules import adownloader, logging_util
  File "/home/yuan/src/az/modules/adownloader.py", line 12
    logging.info(f'START. APKS TO DOWNLOAD: {number}')
                                                    ^
SyntaxError: invalid syntax

So how can I fix this ? Or is there something wrong in my installation steps?

**Comment by jy5380** [comment]
I have solved this problem, the cause is the format printing.

**Comment by ArtemKushnerov** [comment]
Yes, the version in requirements wasn’t precise, it requires Python 3.6. Fixed readme.

**Comment by MiloAnthony** [comment]
@jy5380 How did you fix it? I have encountered the same problem although I updated Python to 3.6.

**Comment by MiloAnthony** [comment]
@ArtemKushnerov I have solved it, thank you.
