### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'Hashable'

### ISSUE THREAD

**Issue by Flyroxx** [ArtemKushnerov/az#78]
Tried this command : az -n 1 -d 2020-01-01: -s :5000000  -m play.google.com
but i keep getting the error "AttributeError: module 'collections' has no attribute 'Hashable'".
Full log of the error:

Traceback (most recent call last):
  File "/home/yahia/.local/bin/az", line 8, in <module>
    sys.exit(run())
  File "/home/yahia/.local/lib/python3.10/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/yahia/.local/lib/python3.10/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/yahia/.local/lib/python3.10/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yahia/.local/lib/python3.10/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/yahia/.local/lib/python3.10/site-packages/modules/main.py", line 49, in run
    logging_util.setup_logging()
  File "/home/yahia/.local/lib/python3.10/site-packages/modules/logging_util.py", line 9, in setup_logging
    logging.config.dictConfig(yaml.safe_load(f.read()))
  File "/home/yahia/.local/lib/python3.10/site-packages/yaml/__init__.py", line 94, in safe_load
    return load(stream, Loader=SafeLoader)
  File "/home/yahia/.local/lib/python3.10/site-packages/yaml/__init__.py", line 73, in load
    return loader.get_single_data()
  File "/home/yahia/.local/lib/python3.10/site-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/home/yahia/.local/lib/python3.10/site-packages/yaml/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/home/yahia/.local/lib/python3.10/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/home/yahia/.local/lib/python3.10/site-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/home/yahia/.local/lib/python3.10/site-packages/yaml/constructor.py", line 126, in construct_mapping
    if not isinstance(key, collections.Hashable):
AttributeError: module 'collections' has no attribute 'Hashable'

**Comment by embeddinglayer** [comment]
```bash
pip install --upgrade PyYaml
```
Upgrade your PyYaml version
